name: biblioteca_virtual
description: Projeto de biblioteca virtual em Dart
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  lints: ^6.0.0
# Caso queira usar pacotes do pub.dev, adicione aqui
# Exemplo: http: ^1.2.0
